### PR TITLE
[GSoC2024] fix cvat-ui error when open a job with issue (#7600)

### LINKED ISSUE #7600: cvat-ui error when open a job with issues
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1. create a issue in a job
2. open the job
3. go to the Jobs
4. click on the job I entered earlier

### Expected Behavior

_No response_

### Possible Solution

The error may be caused by HiddenIssueLabel.

### Context

error:
react-dom.production.min.js:209 Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.Zl [as createPortal] (react-dom.production.min.js:287:319)
    at $Te (hidden-issue-label.tsx:65:12)
    at qi (react-dom.production.min.js:153:146)
    at ys (react-dom.production.min.js:261:496)
    at fl (react-dom.production.min.js:246:265)
    at dl (react-dom.production.min.js:246:194)
    at rl (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Va (react-dom.production.min.js:122:325)

### Environment

_No response_

### PR DESCRIPTION
**Pull request by umangapatel123**
Fixed an issue of error in cvat-ui when a job with issue is opened 

The canvas ready state is not updated when unmounting canvas 
make changes to set canvas ready state to false when canvas is unmounted.

### Motivation and context

Fixes #7600
This change is necessary because it will make sure that the canvas is ready before attaching the issue label to the canvas

### How has this been tested?

Manually

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- ~~[ ] I have increased versions of npm packages if it is necessary~~
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by umangapatel123** [comment]
@nmanovic @bsekachev can you please review this PR?

**Comment by bsekachev** [comment]
Hello, 

Did you try to use existing action `AnnotationActionTypes.CLOSE_JOB`? 
And set `canvasReady` to false when it is dispatched?

**Comment by umangapatel123** [comment]
@bsekachev, No sir. I haven't tried doing that I have just created a new action `AnnotationActionTypes.UPDATE_CANVAS_READY` and dispatched the action when canvas unmountes to set the `canvasReady` to false.

**Comment by umangapatel123** [comment]
also the `AnnotationActionTypes.CLOSE_JOB` is not dispatched when you go directly from the annotation page to jobs page

**Comment by bsekachev** [comment]
We do not need extra action, because CLOSE_JOB already exists and used to handle canvas:
image

> also the AnnotationActionTypes.CLOSE_JOB is not dispatched when you go directly from the annotation page to jobs page

There is code in `cvat-ui/src/components/annotation-page/annotation-page.tsx`

```js
            if (!history.location.pathname.includes('/jobs')) {
                closeJob();
            }
```

written 4 years ago. Jobs page has been added much later. Perhaps we need to reconsider this fragment. Unfortunately, I do not remember why we avoid closing the job when pathname contains `jobs`. Probably to avoid removing `job` instance with annotations, etc. from the client, when component somehow get's unmounted. And we may write a better condition to handle the case.

What is more, the fact that `closeJob()` is one more bug (I suspect that it may lead to memory leaking).

**Comment by bsekachev** [comment]
Hello @umangapatel123 
Do you have any plans regarding the pull request?

**Comment by bsekachev** [comment]
Please, let us know if you are ready to continue.

**Pull request closed without merging**
