### PR TITLE
Fix unstable 2E2 tests

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context
Need to fix from time to time failing `issue_2473_import_annotations_frames_dots_in_name.js` and `registration_involved/*` tests

Notes on Registration involved tests:
1. The Problem: On login page, after several continious registrations and logouts, link to register page sometimes become detached: 
image

2. Possible solutions:
    1. Cypress suggests that if our element become detached, we need to ensure it is not re-rendered in between assertions. With this pr, elements on login form are rendered only once as we can see in Profiler. But that didnt solve the problem.
   image

    3. Cypress [blog](https://www.cypress.io/blog/2020/07/22/do-not-get-too-detached/) suggests us to wait for all requests on page and use rety-ability before doing something. In this case both of waitings didn't work, element somehow becomes detached after all requests are finished, its present in DOM but detaches right before click
    4. Updating to React 18 with React-router v6 seems solving the problem,  but it's a task for later
    5. Cypress repo has an [issue](https://github.com/cypress-io/cypress/issues/7306) about detached elements. This behavior considered as bug and should be fixed with new major version (11).  From the issue we can understood the current best workaround is wait for elements to be stable.
   
Let's keep the workaround for now. In the future we can update to React 18 or Cypress 11 and remove `wait`

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] ~~I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file~~
- [ ] ~~I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly~~
- [ ] ~~I have added tests to cover my changes~~
- [ ] I~~have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~~
- [ ] ~~I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by klakhov** [comment]
@bsekachev Could you review this patch? It contains a bit of rendering optimization, but in the end it seems only waiting for page to load worked for registration-involved tests

**Comment by bsekachev** [comment]
@klakhov 

Please, try this patch: https://github.com/cvat-ai/cvat/tree/bs/fix_unstable_tests
It does not re-render login page when open first time or do logout and looks simpler.

In this way I personally do not think that mixing logic of shouldComponentUpdate and didComponentUpdate is a good idea. 
What is more, it does not help as I understand because we anyway have ``wait`` in test cases.

**Review by bsekachev — APPROVED** [review]
Okay, let's try to merge it and see if it helps

**Pull request merged**
