### PR TITLE
[WIP] Add button to switch between RGB color channels

### PR DESCRIPTION
**Pull request by ddx-day**
In training models sometimes the behavior of color images is different in different color channels. In order to add labels to images where this is the case this creates a button that makes a grey scale version of the image exclusively in the Red, Green or Blue channel.

### Motivation and context
Allows tagging images using RGB channels on a grey scale version of the image

### How has this been tested?
Added a test which iterates through each of the color channels and tests that it changes the canvas and that
the red, green and blue channels change the behavior on red, green and blue example images as expected.

### Checklist
- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [x] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by nmanovic** [comment]
@ddx-day , thanks for the contribution! Please give us some time to review. I will add the PR on our internal kanban board.

**Comment by ddx-day** [comment]
Thanks. This was actually created by someone at the company who has subsequently left, but we the functionality is very useful, and we would like to make it available for others

**Review by klakhov — COMMENTED** [review]
Thanks for contribution, functionality seems to work fine but I have few suggestions.

In CVAT, we have integrated OpenCV.js library which compiled version I belive can do color channel operations better & faster than doing it in simple js way. Besides in [opencv-control.tsx](https://github.com/opencv/cvat/blob/develop/cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/opencv-control.tsx) there is concept of `ImageModifier` which can be used to combine channel modifier with Histogram Equalization. So I suggest to implement this functionality using OpenCV.js like its done to Histogram Equalization. You can create appropriate `.ts` class in [opencv-wrapper](https://github.com/opencv/cvat/tree/develop/cvat-ui/src/utils/opencv-wrapper) so there is no need to use `chooseColor.js` with lots of eslint-disable comments. 
Then we can add channel switcher into `Images` tab of OpenCV tool. 

Other comments about the feature:
1. When some channel filter is active, it sould be highlighted
image
2. Using different shortcut modifiers `Alt+R`, `Ctrl+G` etc. is quite confusing. I think we need to use same modifiers for each filter, `Alt` or `Ctrl` for each one. 
3. Please update headers for each file, just add `// Copyright (C) 2022 CVAT.ai Corporation` after Intel header. Also please add a line to CHANGELOG.md

**Comment by ddx-day** [comment]
Hi. We are discussing internally whether the OpenCV functionality would be equivalent and/or better and we will decide if we want to make the changes or not

**Comment by klakhov** [comment]
I will close this pr for now. If you decide to implement this functionality, feel free to reopen.

**Comment by DxTa** [comment]
I think this direction is also beneficial also to introduce multi-modality switching as well? @klakhov if this is also valid and aligned with your vision, I can try to continue this PR or maybe already partially supported via idea of contextual image (though overlapping images might be still beneficial)

**Pull request closed without merging**
