### PR TITLE
[GSoC2024] update helm chart: Add common sub-chart

### LINKED ISSUE #7449: Helm Chart version mismatch between postgres and redis
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. With `values.yaml` containing

```
postgresql:
  enabled: true
redis:
  enabled: true
```
and the default versions from `Chart.yaml`

```
dependencies:
  - name: postgresql
    version: "12.1.*"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "18.5.*"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
```

`helm upgrade --install`

results in

`Error: UPGRADE FAILED: template: cvat/charts/redis/templates/master/service.yaml:12:14: executing "cvat/charts/redis/templates/master/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name`

`Chart.lock`

```
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.15
- name: nuclio
  repository: https://nuclio.github.io/nuclio/charts
  version: 0.12.1
- name: vector
  repository: https://helm.vector.dev
  version: 0.19.2
- name: clickhouse
  repository: https://charts.bitnami.com/bitnami
  version: 4.1.16
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.60.6
- name: traefik
  repository: https://helm.traefik.io/traefik
  version: 25.0.0
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.5.0
digest: sha256:f2002bbe6d04d607b81b373991c1a05ec533e3da5edbc92b5d082d23d50656ca
generated: "2024-02-07T16:46:49.280424046+01:00"
```

### Expected Behavior

Helm installation should run successfully

### Possible Solution

upgrade postgres version in Chart.yaml

```
dependencies:
  - name: postgresql
    version: "12.9.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
```

as suggest in [this issue](https://github.com/bitnami/charts/issues/20504) resolves the issue.

`Chart.lock` no looks like this

```
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.9.0
- name: nuclio
  repository: https://nuclio.github.io/nuclio/charts
  version: 0.12.1
- name: vector
  repository: https://helm.vector.dev
  version: 0.19.2
- name: clickhouse
  repository: https://charts.bitnami.com/bitnami
  version: 4.1.16
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.60.6
- name: traefik
  repository: https://helm.traefik.io/traefik
  version: 25.0.0
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.5.0
digest: sha256:21c9226320b0d6112468d18c0d4be7117c17e82f83801fab2fcb691f430c657c
generated: "2024-02-07T16:17:50.197680436+01:00"

```

for the redis `Chart.lock` we get

```
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.13.3
digest: sha256:9a971689db0c66ea95ac2e911c05014c2b96c6077c991131ff84f2982f88fb83
generated: "2023-10-19T12:32:36.790999138Z"
```

and postgres `Chart.lock`

```
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.9.0
digest: sha256:416ad278a896f0e9b51d5305bef5d875c7cca6fbb64b75e1f131b04763e2aff9
generated: "2023-08-22T14:27:37.862238+02:00"
```

These versions of common seem to be more compatible.

### Context

_No response_

### Environment

_No response_

### LINKED ISSUE #7507: Helm can't install with analytics.enabled false
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. set analytics.enabled to false in values.yaml 
2. run helm install

### Expected Behavior

Install without analytics

### Possible Solution

This problem doesn't exist in v2.8.0

### Context

I got this error
`Error: template: cvat/charts/redis/templates/master/service.yaml:12:14: executing "cvat/charts/redis/templates/master/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name`

### Environment

_No response_

### PR DESCRIPTION
**Pull request by abhi-bhatra**
### Motivation and context

There has been multiple issue coming due to conflict in common chart version of Redis and Postgresql.
Fixes #7449 
Fixes #7507 

### How has this been tested?

1. Apply Helm chart with analytics enabled (*Result: helm chart working*)
2. Now, try to run helm chart again, with analytics disabled (*Result: helm chart will get an error*)
Below is the error: 
```shell
Error: template: cvat/charts/redis/templates/master/service.yaml:12:14: executing "cvat/charts/redis/templates/master/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
helm.go:84: [debug] template: cvat/charts/redis/templates/master/service.yaml:12:14: executing "cvat/charts/redis/templates/master/service.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: cvat/charts/postgresql/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have created a changelog fragment 
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by nmanovic** [comment]
@abhi-bhatra , could you please add a link into CHANGELOG.md? See instructions inside the file on how to do that.

**Comment by azhavoro** [comment]
@abhi-bhatra thanks for the contribution
I have one question:
Are you sure that the current versions of Redis, Postgresql and Clickhouse charts will be compatible with all future versions of common chart v2.x.x?

**Comment by nmanovic** [comment]
@abhi-bhatra , will you be able to complete the PR?

**Comment by abhi-bhatra** [comment]
HI @nmanovic I am working on it, and will complete it by today EOD

**Comment by abhi-bhatra** [comment]
@azhavoro I have pinned the common chart version, but I would like you to point me where to add test for helm charts ?

**Comment by azhavoro** [comment]
> @azhavoro I have pinned the common chart version, but I would like you to point me where to add test for helm charts ?
> 
> Should I create a bash script ?

I think it can be separate job in this workflow https://github.com/opencv/cvat/blob/develop/.github/workflows/helm.yml

**Comment by abhi-bhatra** [comment]
Thanks @azhavoro I am adding test case in this workflow. Thanks for guiding me !

**Comment by abhi-bhatra** [comment]
@azhavoro I have added a simple test case in the workflow, Can you review it ?

**Comment by azhavoro** [comment]
@abhi-bhatra Hello, the test example is not working, could you please fix it?

**Comment by azhavoro** [comment]
I can't merge this PR due to failed tests

**Pull request closed without merging**
