### PR TITLE
Use exceptions instead of HTML responses with error statuses

### PR DESCRIPTION
**Pull request by SpecLad**
### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have created a changelog fragment 
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- ~~[ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~~
- ~~[ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
@SpecLad, if you're working on this, please check if you can improve the situation with output data in the error, asked here: https://github.com/cvat-ai/cvat/pull/8348#issuecomment-2378797877

> Would it be hard to improve formatting for the validation error? Like return only the stuff thats insize string=?. I suppose we have lots of cases now when we can get it. On the second thought I belive its easier to UI to parse it for better UX, we already have some handling for such cases. Maybe not really relevant for now

**Comment by SpecLad** [comment]
@zhiltsov-max I don't understand what that comment is talking about. Is it some specific error? What's `string=`?

**Comment by klakhov** [comment]
@SpecLad 
When I was testing the honeypots patch Ive seen different validation errors. For example this one, when Im trying to create honeypots task from video file:
image

The Idea was to improve the UX of the error. It seems we need to show only stuff that is written inside `string=` part of the error. As everything else seems as unnecessary information to the user

**Comment by SpecLad** [comment]
Ah, I see. I think that exception is coming from inside an RQ job. I do think we have some deficiencies in how those exceptions are presented to the user, but fixing that would be out of scope for this PR.

That said, I find it odd that that particular error would be thrown from an RQ job. It seems like it's just validating input parameters; it would be better to do that in the view _before_ starting the RQ job. Not only is that more efficient, but it should also fix the presentation problem.

**Comment by zhiltsov-max** [comment]
> It seems like it's just validating input parameters; it would be better to do that in the view before starting the RQ job.

Not everything can be validated before processing. For instance, in this case, you'd need to know that the input is video (it's possible to check, sure). It can only be checked after the `Upload-Finished` data request. There are other checks that depend on the actual data provided, like depending on frame count.

**Comment by SpecLad** [comment]
> For instance, in this case, you'd need to know that the input is video (it's possible to check, sure). It can only be checked after the `Upload-Finished` data request.

Okay, that's a fair point.

**Comment by SpecLad** [comment]
I don't have time to finish this PR right now; I'll try to come back to it later.

**Pull request closed without merging**
