### PR TITLE
Add CVAT_HOST to CSRF_TRUSTED_ORIGINS

### PR DESCRIPTION
**Pull request by pktiuk**
Closes: https://github.com/opencv/cvat/issues/6321

### Motivation and context

CVAT uses `django.middleware.csrf.CsrfViewMiddleware`, but it does not set variable `CSRF_TRUSTED_ORIGINS`. It may cause some issues. Especially in configs with changed traefik configurations (links with http:// and https:// are treated as separate entries and may cause blocking some requests to server)

### How has this been tested?

It was built and launched with docker

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
~~- [ ] I have updated the documentation accordingly~~
~~- [ ] I have added tests to cover my changes~~
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
~~- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by pktiuk** [comment]
@azhavoro   
Will this change make it for the next release?

**Comment by pktiuk** [comment]
@bsekachev 

Could I get any feedback?

**Comment by jevansbio** [comment]
I had the issue and implementing this PR fixed them

**Comment by pktiuk** [comment]
@azhavoro   
Could I get some feedback about this PR?

**Comment by brunodrugowick** [comment]
Is there a workaround available while this is not merged other than cherry-picking this commit?

**Comment by pktiuk** [comment]
@brunodrugowick     
I am not aware of any other fix addressing this issue.   
I have no idea why this is not merged yet.

**Comment by bsekachev** [comment]
Hi @pktiuk , 

It is not merged yet, because it is not totally clear for now, why we need to modify CSRF_TRUSTED_ORIGIN list.

According to [Django documentation](https://docs.djangoproject.com/en/4.2/ref/csrf/#:~:text=How%20it%20works,with%20the%20response%20whenever%20django.):

> CsrfViewMiddleware verifies the Origin header, if provided by the browser, against the current host and the CSRF_TRUSTED_ORIGINS setting. This provides protection against cross-subdomain attacks.

As I understand, it means, that there is not necessarity to specify CVAT_HOST in CSRF_TRUSTED_ORIGINS, because it is already included _"by default"_. On the other hand it does not disable CSRF token check itself. According to the documentation, check is triggered anyway:

> For all incoming requests that are not using HTTP GET, HEAD, OPTIONS or TRACE, a CSRF cookie must be present, and the ‘csrfmiddlewaretoken’ field must be present and correct. If it isn’t, the user will get a 403 error.

and I am not really sure how it solves your problem. My only assumption for now is that somehow in your configuration server origin is not the same as client origin. 

Finally, we have https://app.cvat.ai where .. we do not configure CSRF_TRUSTED_ORIGIN and it works. 

P.S. I am more frontend than backend dev, and maybe misunderstood something

**Comment by jloebl** [comment]
> My only assumption for now is that somehow in your configuration server origin is not the same as client origin.

As we see by the linked issues, more people are facing this issue after updating cvat. Sadly, we cant use the update if we can not manage users anymore. This is a huge deal breaker!

**Comment by pktiuk** [comment]
Hello @bsekachev ,
Sorry for delay. I think I can explain why this fix work (this is just my guess, not 100% sure).  
As you can see in [django docs](https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS) 

> These checks prevent, for example, a POST request from subdomain.example.com from succeeding against api.example.com. If you need cross-origin unsafe requests, continuing the example, add 'https://subdomain.example.com' to this list (and/or http://... if requests originate from an insecure page).

variable `CSRF_TRUSTED_ORIGINS` differentiates between HTTP and HTTPS origins. In our case this may be problematic, when we use `docker-compose.https.yml`, because Django generates http, which are later encrypted by traefik and it gets back responses in https. My changes adds both http and https to trusted origins to be sure, that both configurations work.

**Comment by baudneo** [comment]
Using CVAT and cloudflared causes the CSRF 403 Forbidden on Django admin page POSTS. This PR should be merged as my setup would seem to be common. Users who want/need control over CORS/CSRF, should have it.

**Review by brunodrugowick — APPROVED** [review]

**Comment by baudneo** [comment]
Just a quick note. It would be good to add CVAT_HOST to environment for cvat_server in docker compose .yml file.

 Users may not notice that its missing and keep getting the card 403.

**Comment by pktiuk** [comment]
@baudneo   
`CVAT_HOST` is meant to be defined by administrator during deployment.    
https://opencv.github.io/cvat/docs/administration/basics/installation/

**Comment by baudneo** [comment]
> @baudneo `CVAT_HOST` is meant to be defined by administrator during deployment. https://opencv.github.io/cvat/docs/administration/basics/installation/

Understood, I mean adding

`${CVAT_HOST:-localhost}`
To the cvat_server environment so that CVAT_HOST is passed through to container.

**Comment by pktiuk** [comment]
> > @baudneo `CVAT_HOST` is meant to be defined by administrator during deployment. https://opencv.github.io/cvat/docs/administration/basics/installation/
> 
> Understood, I mean adding
> 
> `${CVAT_HOST:-localhost}` To the cvat_server environment so that CVAT_HOST is passed through to container.

Sorry, but I don't know what do you mean. `${CVAT_HOST:-localhost}` is already added To the cvat_server
Just check docker-compose.yml https://github.com/pktiuk/cvat/blob/8520aa322d7455e1d453aab12a83ea4ff0d25a82/docker-compose.yml#L57

**Comment by baudneo** [comment]
> > > @baudneo `CVAT_HOST` is meant to be defined by administrator during deployment. https://opencv.github.io/cvat/docs/administration/basics/installation/
> > 
> > 
> > Understood, I mean adding
> > `${CVAT_HOST:-localhost}` To the cvat_server environment so that CVAT_HOST is passed through to container.
> 
> Sorry, but I don't know what do you mean. `${CVAT_HOST:-localhost}` is already added To the cvat_server Just check docker-compose.yml https://github.com/pktiuk/cvat/blob/8520aa322d7455e1d453aab12a83ea4ff0d25a82/docker-compose.yml#L57

So it is, sorry about that. I rolled a docker compose 2 days ago and I must of accidentally deleted that line. I had to add it in myself so I thought it wasn't in the compose file.

**Comment by baudneo** [comment]
> > > @baudneo `CVAT_HOST` is meant to be defined by administrator during deployment. https://opencv.github.io/cvat/docs/administration/basics/installation/
> > 
> > 
> > Understood, I mean adding
> > `${CVAT_HOST:-localhost}` To the cvat_server environment so that CVAT_HOST is passed through to container.
> 
> Sorry, but I don't know what do you mean. `${CVAT_HOST:-localhost}` is already added To the cvat_server Just check docker-compose.yml https://github.com/pktiuk/cvat/blob/8520aa322d7455e1d453aab12a83ea4ff0d25a82/docker-compose.yml#L57

Hi, in your reply it has your fork as the source. In the cvat repo docker-compose.yml `CVAT_HOST` is missing from `environment:` -> https://github.com/opencv/cvat/blob/d497bb6a90dd3c9625c3c8e8f73278019e21983d/docker-compose.yml#L56

**Comment by pktiuk** [comment]
@brunodrugowick   @bsekachev     
I see that this PR is approved, so can it be merged?

@baudneo I think you should mark your older comments as outdated to avoid spam.

**Comment by kodai2199** [comment]
In my experience I was running CVAT using HTTP, but accessing it using a nginx HTTPS proxy and proxied cloudflare dns. After setting up  CVAT to use HTTPS natively, and updating the nginx configuration, the issue was resolved without additional fixes.

**Comment by olliethomas** [comment]
Hi, is there anything that I can help with to get this merged? The issue that this resolves is stopping us from deploying CVAT on our infrastructure :(

**Comment by marc31** [comment]
> In my experience I was running CVAT using HTTP, but accessing it using a nginx HTTPS proxy and proxied cloudflare dns. After setting up CVAT to use HTTPS natively, and updating the nginx configuration, the issue was resolved without additional fixes.

I'm in the same situation, but in my infrastructure, I can't use CVAT to directly manage its certificate. Do you think this will be merged?

**Comment by marc31** [comment]
I'm deploying to a server, and my CVAT_HOST variable correctly holds the value of the final domain. 
I'm using CVAT's Docker Compose for deployment without the HTTPS component, as ports 80 and 443 are already allocated by an NGINX server acting as a reverse proxy.
Without including the CSRF_TRUSTED_ORIGINS variable with my final domain, including the protocol, I encounter CSRF errors.

**Comment by brunodrugowick** [comment]
> I'm deploying to a server, and my CVAT_HOST variable correctly holds the value of the final domain. I'm using CVAT's Docker Compose for deployment without the HTTPS component, as ports 80 and 443 are already allocated by an NGINX server acting as a reverse proxy. Without including the CSRF_TRUSTED_ORIGINS variable with my final domain, including the protocol, I encounter CSRF errors.

Ah, you're right. I do have to set `CSRF_TRUSTED_ORIGINS`: 

```shell
#!/bin/bash

if [[ -z $1 ]]; then
    echo "internal or external?"
    exit 1
elif [[ $1 == "internal" ]]; then
    export CVAT_HOST=192.168.1.5
elif [[ $1 == "external" ]]; then
    export CVAT_HOST=cvat.whatever.com
    export CSRF_TRUSTED_ORIGINS=cvat.whatever.com
fi

#docker-compose up -d

#export CVAT_NUCLIO_DEFAULT_TIMEOUT=600
docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
```

**Comment by marc31** [comment]
> > I'm deploying to a server, and my CVAT_HOST variable correctly holds the value of the final domain. I'm using CVAT's Docker Compose for deployment without the HTTPS component, as ports 80 and 443 are already allocated by an NGINX server acting as a reverse proxy. Without including the CSRF_TRUSTED_ORIGINS variable with my final domain, including the protocol, I encounter CSRF errors.
> 
> Ah, you're right. I do have to set `CSRF_TRUSTED_ORIGINS`:
> 
> ```shell
> #!/bin/bash
> 
> if [[ -z $1 ]]; then
>     echo "internal or external?"
>     exit 1
> elif [[ $1 == "internal" ]]; then
>     export CVAT_HOST=192.168.1.5
> elif [[ $1 == "external" ]]; then
>     export CVAT_HOST=cvat.whatever.com
>     export CSRF_TRUSTED_ORIGINS=cvat.whatever.com
> fi
> 
> #docker-compose up -d
> 
> #export CVAT_NUCLIO_DEFAULT_TIMEOUT=600
> docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
> ```

Which version of CVAT are you using? I'm surprised because when I search throughout the entire project for CSRF_TRUSTED_ORIGINS, I only find one reference in the file cvat/cvat/settings/development.py, indicating that Django employs it only when is running in dev mode.

Additionally, in the docker-compose.yml files, there isn't anything specified for the container:

```yml
services:
    ...
    cvat_server:
        ...
        environment:
            ...
            CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
            ...
        ...
    ...
...        
```  

This implies that the variable you're assigning is never passed to the container and therefore isn't utilized.

**Comment by nmanovic** [comment]
I will close the PR because the change looks unnecessary.

**Comment by marc31** [comment]
@nmanovic Can you explain why this PR looks unnecessary please ?

**Comment by brunodrugowick** [comment]
> > > I'm deploying to a server, and my CVAT_HOST variable correctly holds the value of the final domain. I'm using CVAT's Docker Compose for deployment without the HTTPS component, as ports 80 and 443 are already allocated by an NGINX server acting as a reverse proxy. Without including the CSRF_TRUSTED_ORIGINS variable with my final domain, including the protocol, I encounter CSRF errors.
> > 
> > 
> > Ah, you're right. I do have to set `CSRF_TRUSTED_ORIGINS`:
> > ```shell
> > #!/bin/bash
> > 
> > if [[ -z $1 ]]; then
> >     echo "internal or external?"
> >     exit 1
> > elif [[ $1 == "internal" ]]; then
> >     export CVAT_HOST=192.168.1.5
> > elif [[ $1 == "external" ]]; then
> >     export CVAT_HOST=cvat.whatever.com
> >     export CSRF_TRUSTED_ORIGINS=cvat.whatever.com
> > fi
> > 
> > #docker-compose up -d
> > 
> > #export CVAT_NUCLIO_DEFAULT_TIMEOUT=600
> > docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
> > ```
> 
> Which version of CVAT are you using? I'm surprised because when I search throughout the entire project for CSRF_TRUSTED_ORIGINS, I only find one reference in the file cvat/cvat/settings/development.py, indicating that Django employs it only when is running in dev mode.
> 
> Additionally, in the docker-compose.yml files, there isn't anything specified for the container:
> 
> ```yaml
> services:
>     ...
>     cvat_server:
>         ...
>         environment:
>             ...
>             CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
>             ...
>         ...
>     ...
> ...        
> ```
> 
> This implies that the variable you're assigning is never passed to the container and therefore isn't utilized.

Hi, I'm in `2.11.0`. Apparently I added this var in one more place (other than my own script): 

```shell
 >> grep -rnw . -e 'CSRF_TRUSTED_ORIGINS'
./docker-compose.yml:260:      CSRF_TRUSTED_ORIGINS: <redacted>
./run-proxy.sh:10:    export CSRF_TRUSTED_ORIGINS=<redacted>
./components/serverless/run-proxy.sh:10:    export CSRF_TRUSTED_ORIGINS=<redacted>
./cvat/settings/development.py:30:CSRF_TRUSTED_ORIGINS = [UI_URL]
```

I see that `CSRF_TRUSTED_ORIGINS` is an option from Django and CVAT uses Django:

```shell
/path/to/cvat ((HEAD detached at v2.11.0))
 >> grep -rnw . -e 'django=='
./.github/workflows/pylint.yml:26:              $(egrep "^django==" ./cvat/requirements/base.txt)
/path/to/cvat ((HEAD detached at v2.11.0))
 >> cat cvat/requirements/base.txt | grep django==
django==4.2.6
```

I don't know much about Django, but I have a lot of experience with Spring (JVM world) and you can change A LOT of things without touching the source code, only by setting runtime environment variables, so I wouldn't be surprised that this has an effect even though you can't find references in CVAT's source code.

Also I can see empirically that setting it does have an effect:

```shell
/path/to/cvat ((HEAD detached at v2.11.0))
 >> ./run-proxy.sh external
WARNING: Found orphan containers (cvat_redis) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
cvat_redis_ondisk is up-to-date
cvat_redis_inmem is up-to-date
cvat_db is up-to-date
cvat_opa is up-to-date
Starting cvat_grafana ...
traefik is up-to-date
cvat_clickhouse is up-to-date
nuclio is up-to-date
cvat_worker_import is up-to-date
cvat_utils is up-to-date
cvat_worker_quality_reports is up-to-date
cvat_worker_analytics_reports is up-to-date
cvat_worker_webhooks is up-to-date
cvat_worker_export is up-to-date
cvat_worker_annotation is up-to-date
cvat_server is up-to-date
cvat_vector is up-to-date
Starting cvat_grafana ... done
/path/to/cvat ((HEAD detached at v2.11.0))
 >> wget <redacted - previously cvat.whatever.com>
--2024-04-27 14:16:20--  http://cvat.whatever.com/
Resolving cvat.whatever.com (cvat.whatever.com)... 2606:4700:3036::ac43:cb79, 2606:4700:3035::6815:1652, 104.21.22.82, ...
Connecting to cvat.whatever.com (cvat.whatever.com)|2606:4700:3036::ac43:cb79|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html          [ <=>   ]   1,24K  --.-KB/s    in 0s

2024-04-27 14:16:20 (120 MB/s) - ‘index.html’ saved [1265]

/path/to/cvat ((HEAD detached at v2.11.0))
 >> wget 192.168.0.17:8080
--2024-04-27 14:16:33--  http://192.168.0.17:8080/
Connecting to 192.168.0.17:8080... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-04-27 14:16:33 ERROR 404: Not Found.

/path/to/cvat ((HEAD detached at v2.11.0))
 >> ./run-proxy.sh internal
WARNING: Found orphan containers (cvat_redis) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
cvat_clickhouse is up-to-date
cvat_redis_inmem is up-to-date
Recreating traefik ...
cvat_db is up-to-date
cvat_redis_ondisk is up-to-date
Recreating cvat_grafana ...
nuclio is up-to-date
cvat_opa is up-to-date
cvat_vector is up-to-date
cvat_worker_annotation is up-to-date
cvat_utils is up-to-date
cvat_worker_import is up-to-date
cvat_worker_quality_reports is up-to-date
cvat_worker_export is up-to-date
Recreating traefik      ... done
Recreating cvat_grafana ... done
Recreating cvat_server  ... done
Recreating cvat_ui      ... done
/path/to/cvat ((HEAD detached at v2.11.0))
 >> wget cvat.whatever.com
--2024-04-27 14:16:51--  http://cvat.whatever.com/
Resolving cvat.whatever.com (cvat.whatever.com)... 2606:4700:3035::6815:1652, 2606:4700:3036::ac43:cb79, 104.21.22.82, ...
Connecting to cvat.whatever.com (cvat.whatever.com)|2606:4700:3035::6815:1652|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-04-27 14:16:51 ERROR 404: Not Found.

/path/to/cvat ((HEAD detached at v2.11.0))
 >> wget 192.168.0.17:8080
--2024-04-27 14:16:55--  http://192.168.0.17:8080/
Connecting to 192.168.0.17:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1265 (1,2K) [text/html]
Saving to: ‘index.html.1’

index.html.1    100%[======>]   1,24K  --.-KB/s    in 0s

2024-04-27 14:16:55 (406 MB/s) - ‘index.html.1’ saved [1265/1265]
```

**Comment by brunodrugowick** [comment]
> > > I'm deploying to a server, and my CVAT_HOST variable correctly holds the value of the final domain. I'm using CVAT's Docker Compose for deployment without the HTTPS component, as ports 80 and 443 are already allocated by an NGINX server acting as a reverse proxy. Without including the CSRF_TRUSTED_ORIGINS variable with my final domain, including the protocol, I encounter CSRF errors.
> > 
> > 
> > Ah, you're right. I do have to set `CSRF_TRUSTED_ORIGINS`:
> > ```shell
> > #!/bin/bash
> > 
> > if [[ -z $1 ]]; then
> >     echo "internal or external?"
> >     exit 1
> > elif [[ $1 == "internal" ]]; then
> >     export CVAT_HOST=192.168.1.5
> > elif [[ $1 == "external" ]]; then
> >     export CVAT_HOST=cvat.whatever.com
> >     export CSRF_TRUSTED_ORIGINS=cvat.whatever.com
> > fi
> > 
> > #docker-compose up -d
> > 
> > #export CVAT_NUCLIO_DEFAULT_TIMEOUT=600
> > docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
> > ```
> 
> Which version of CVAT are you using? I'm surprised because when I search throughout the entire project for CSRF_TRUSTED_ORIGINS, I only find one reference in the file cvat/cvat/settings/development.py, indicating that Django employs it only when is running in dev mode.
> 
> Additionally, in the docker-compose.yml files, there isn't anything specified for the container:
> 
> ```yaml
> services:
>     ...
>     cvat_server:
>         ...
>         environment:
>             ...
>             CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
>             ...
>         ...
>     ...
> ...        
> ```
> 
> This implies that the variable you're assigning is never passed to the container and therefore isn't utilized.

Hi, I'm in `2.11.0`. Apparently I added this var in one more place (other than my own script): 

```shell
 >> grep -rnw . -e 'CSRF_TRUSTED_ORIGINS'
./docker-compose.yml:260:      CSRF_TRUSTED_ORIGINS: <redacted>
./run-proxy.sh:10:    export CSRF_TRUSTED_ORIGINS=<redacted>
./components/serverless/run-proxy.sh:10:    export CSRF_TRUSTED_ORIGINS=<redacted>
./cvat/settings/development.py:30:CSRF_TRUSTED_ORIGINS = [UI_URL]
```

I see that `CSRF_TRUSTED_ORIGINS` [is an option from Django](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS) and CVAT uses Django:

```shell
/path/to/cvat ((HEAD detached at v2.11.0))
 >> grep -rnw . -e 'django=='
./.github/workflows/pylint.yml:26:              $(egrep "^django==" ./cvat/requirements/base.txt)
/path/to/cvat ((HEAD detached at v2.11.0))
 >> cat cvat/requirements/base.txt | grep django==
django==4.2.6
```

I don't know much about Django, but I have a lot of experience with Spring (JVM world) and you can change A LOT of things without touching the source code, only by setting runtime environment variables, so I wouldn't be surprised that this has an effect even though you can't find references in CVAT's source code.

Also I can see empirically that setting it does have an effect:

```shell
/path/to/cvat ((HEAD detached at v2.11.0))
 >> ./run-proxy.sh external
WARNING: Found orphan containers (cvat_redis) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
cvat_redis_ondisk is up-to-date
cvat_redis_inmem is up-to-date
cvat_db is up-to-date
cvat_opa is up-to-date
Starting cvat_grafana ...
traefik is up-to-date
cvat_clickhouse is up-to-date
nuclio is up-to-date
cvat_worker_import is up-to-date
cvat_utils is up-to-date
cvat_worker_quality_reports is up-to-date
cvat_worker_analytics_reports is up-to-date
cvat_worker_webhooks is up-to-date
cvat_worker_export is up-to-date
cvat_worker_annotation is up-to-date
cvat_server is up-to-date
cvat_vector is up-to-date
Starting cvat_grafana ... done
/path/to/cvat ((HEAD detached at v2.11.0))
 >> wget <redacted - previously cvat.whatever.com>
--2024-04-27 14:16:20--  http://cvat.whatever.com/
Resolving cvat.whatever.com (cvat.whatever.com)... 2606:4700:3036::ac43:cb79, 2606:4700:3035::6815:1652, 104.21.22.82, ...
Connecting to cvat.whatever.com (cvat.whatever.com)|2606:4700:3036::ac43:cb79|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html          [ <=>   ]   1,24K  --.-KB/s    in 0s

2024-04-27 14:16:20 (120 MB/s) - ‘index.html’ saved [1265]

/path/to/cvat ((HEAD detached at v2.11.0))
 >> wget 192.168.0.17:8080
--2024-04-27 14:16:33--  http://192.168.0.17:8080/
Connecting to 192.168.0.17:8080... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-04-27 14:16:33 ERROR 404: Not Found.

/path/to/cvat ((HEAD detached at v2.11.0))
 >> ./run-proxy.sh internal
WARNING: Found orphan containers (cvat_redis) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
cvat_clickhouse is up-to-date
cvat_redis_inmem is up-to-date
Recreating traefik ...
cvat_db is up-to-date
cvat_redis_ondisk is up-to-date
Recreating cvat_grafana ...
nuclio is up-to-date
cvat_opa is up-to-date
cvat_vector is up-to-date
cvat_worker_annotation is up-to-date
cvat_utils is up-to-date
cvat_worker_import is up-to-date
cvat_worker_quality_reports is up-to-date
cvat_worker_export is up-to-date
Recreating traefik      ... done
Recreating cvat_grafana ... done
Recreating cvat_server  ... done
Recreating cvat_ui      ... done
/path/to/cvat ((HEAD detached at v2.11.0))
 >> wget cvat.whatever.com
--2024-04-27 14:16:51--  http://cvat.whatever.com/
Resolving cvat.whatever.com (cvat.whatever.com)... 2606:4700:3035::6815:1652, 2606:4700:3036::ac43:cb79, 104.21.22.82, ...
Connecting to cvat.whatever.com (cvat.whatever.com)|2606:4700:3035::6815:1652|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-04-27 14:16:51 ERROR 404: Not Found.

/path/to/cvat ((HEAD detached at v2.11.0))
 >> wget 192.168.0.17:8080
--2024-04-27 14:16:55--  http://192.168.0.17:8080/
Connecting to 192.168.0.17:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1265 (1,2K) [text/html]
Saving to: ‘index.html.1’

index.html.1    100%[======>]   1,24K  --.-KB/s    in 0s

2024-04-27 14:16:55 (406 MB/s) - ‘index.html.1’ saved [1265/1265]
```

**Comment by marc31** [comment]
@brunodrugowick Thanks you

I notice that you have a modified version of the docker-compose.yml file. Indeed, when I look at https://github.com/cvat-ai/cvat/blob/v2.11.0/docker-compose.yml, I see that the string CSRF_TRUSTED_ORIGINS is not present, contrary to what I can see in your grep output.

Regarding the tests with wget, they are not relevant for CSRF_TRUSTED_ORIGINS because it would require POST requests sending response data to a form. However, these tests show us that the CVAT_HOST variable is taken into account to define container labels, allowing Traefik to redirect correctly (cf. https://github.com/cvat-ai/cvat/blob/a942f095edd5ec224f6ab2cc75b35727cc00cc7d/docker-compose.yml#L94). This does not necessarily mean that the variable is accessible for the django container, which you can verify by running:

```bash
docker compose exec -it cvat_server /bin/bash -c 'echo "$CVAT_HOST"'
docker compose exec -it cvat_server /bin/bash -c 'echo "$CSRF_TRUSTED_ORIGINS"'
```

Moreover, even if the variable were accessible in the docker container, it would still need to be added to the python file in the settings directory.

Note: There is another way to make this work without adding the CSRF_TRUSTED_ORIGINS variable to Django's settings, but it would still require setting the USE_X_FORWARDED_HOST variable to true in Django's configuration and modifying Traefik's configuration.

**Comment by pktiuk** [comment]
Things would be much simpler for users if this patch would be merged over half a year ago.

**Comment by st0w** [comment]
I came across this because I was running into the same issue. However I figured out how this can be solved without needing to patch the existing codebase.

Brief background: we are running CVAT on Google Cloud, and have an application load balancer setup that terminates SSL. So we were running into the same issue with CSRF origin failures when POSTing to the admin section.

As has been discussed, part of the issue is that the production CVAT settings do not specify the CSRF_TRUSTED_ORIGINS list, which the development settings do. Setting the variable in the container environment doesn't matter, because it needs to be used by Django - which it isn't in the current CVAT production settings.

The solution is to use an overlay to patch the Django settings, in the same fashion as described in the CVAT documentation for LDAP authentication: https://docs.cvat.ai/docs/administration/advanced/ldap/

The only changes that are needed are as follows:

Create a `local-settings.py` file that will be used to overlay the standard production settings. Contents:

```python
# Overlaying production
from cvat.settings.production import *

CSRF_TRUSTED_ORIGINS = ['https://your.domain.tld']
```

Then create a file for docker-compose to apply the settings; I named it `docker-compose.settings_overlay.local.yml`. Contents:
```YAML
services:
  cvat_server:
    environment:
      DJANGO_SETTINGS_MODULE: settings
    volumes:
      - ./local-settings.py:/home/django/settings.py:ro
```

And then apply it along with the standard `docker-compose.yml` and any other additional configurations (e.g., I also use the external DB config):
```bash
docker compose -f /opt/cvat/cvat/docker-compose.yml \
        -f /opt/cvat/cvat/docker-compose.external_db.local.yml \
        -f /opt/cvat/cvat/docker-compose.settings_overlay.local.yml \
        up -d
```

No source code changes needed, and this will persist across rebuilds, updates, deployments, etc.

**Comment by ducviet00-h2** [comment]
It would help user alot if this PR was merged

**Comment by jpfleischer** [comment]
@st0w , thanks very much for your fix that works extremely well. CVAT is essentially broken when trying to deploy over cloudflare tunnel without doing this fix. It should be included in the main documentation.

**Comment by danbiagini** [comment]
@st0w  this worked great.  I ended up forking github.com/cvat-ai/cvat and creating a light overlay with these changes and also piping in the email parameters to the settings.  I'm going to attempt to keep it up to date with cvat releases.

https://github.com/danbiagini/cvat-light

**Comment by theamarin** [comment]
Hi @nmanovic , thanks for all your work on this project.

> I will close the PR because the change looks unnecessary.

I disagree, the current situation makes setting up and using CVAT much more complicated.
I would appreciate a fix for this.

**Comment by HJJ256** [comment]
@nmanovic @azhavoro @Marishka17 @mdacoca 

This PR seems to be important for handling CSRF_TRUSTED_ORIGINS error on self-hosted CVAT servers. Without these changes, the user has to make unnecessary additions to the docker compose or CVAT codebase, could you please consider reopening and merging this? Or at least provide an alternative working solution that doesn't require jumping through hoops?

**Comment by ledinhtri97** [comment]
This should be merged and help a lot for selfhost cvat

**Comment by SpecLad** [comment]
**To users who are running CVAT behind an external HTTPS reverse proxy:**

In order to fix this problem, you need to configure Traefik to respect the `X-Forwarded-Proto` header coming from the proxy. You can do this by creating a Compose override file like the following:

```yml
services:
  traefik:
    environment:
      TRAEFIK_ENTRYPOINTS_web_FORWARDEDHEADERS_TRUSTEDIPS: <IP-address-of-your-proxy>
```

and adding it to your `docker compose up` command via the `-f` option.

You also need to ensure that the proxy actually sends this header (this depends on your proxy software, but it should be straightforward in most implementations).

This doesn't just fix the CSRF check; it also ensures that when CVAT needs to produce a URL to itself, it correctly uses the `https:` scheme rather than `http:`. It will also make it so that the IP addresses in CVAT logs are the real client addresses, rather than the address of the proxy (provided that the proxy also sends the `X-Forwarded-For` header).

**Pull request closed without merging**
