### PR TITLE
Centralize Python linter/formatter requirements

### PR DESCRIPTION
**Pull request by SpecLad**
### Motivation and context

These are currently duplicated all over the codebase, often with mismatched constraints. Put them all in one requirements file instead.

Fix a few minor issues while I'm at it:

* Constrain black to the current major version to avoid New Year surprises (black can change styles between major versions). Constrain isort too, just in case.

* Remove usages of `egrep`, which is deprecated (and unnecessary here).

### Checklist

- [x] I submit my changes into the `develop` branch
- ~~[ ] I have created a changelog fragment~~ 
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- ~~[ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~~
- ~~[ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

## Summary by CodeRabbit

- **New Features**
	- Introduced new development dependencies, including `black`, `isort`, and `pylint`, to enhance code quality and consistency.
  
- **Bug Fixes**
	- Removed outdated references to development requirements to streamline the installation process.

- **Documentation**
	- Updated comments and structure in various requirements files for clarity.

- **Chores**
	- Deleted obsolete requirements files and simplified existing ones to improve maintainability.

### CODE REVIEW

**Review by zhiltsov-max — COMMENTED** [review]
You should probably update development env setup instructions as well.

**Comment by archibald1418** [comment]
This might seem a bit silly, but adding a spell-checker to CI would also be nice (just as already recommended [here](https://docs.cvat.ai/docs/contributing/development-environment/#setup-the-dependencies), this will enforce correct and unified English spelling in all qualifiers across the codebase. I had this funny thing where I'm searching keywords in the codebase and can't find anything only to later find out that they had been misspelled. Misspellings vary by each author so this might become an issue, too

**Comment by SpecLad** [comment]
> You should probably update development env setup instructions as well.

Alright, updated.

**Comment by SpecLad** [comment]
@archibald1418 Yeah, it would be nice, but that's a big task in its own right.

Incidentally, if you do find misspellings/typos, feel free to submit a PR to fix them.

**Review by zhiltsov-max — APPROVED** [review]

**Pull request merged**
