### PR TITLE
[GSoC2024] added check for the attributes which aren't present for the specified clientID for a conflict of annotation

### LINKED ISSUE #7775: UI Crash on hovering over annotation conflicts which don't have UI representation
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a task from this backup [task.zip](https://github.com/cvat-ai/cvat/files/14984775/task.zip)
2. Go into the review section of the job
3. See the conflicts with the GT job
4. While hovering over the conflicts, suddenly, the UI crashes with the following error message

### Expected Behavior

The conflicting annotation is to be highlighted if available

### Possible Solution

I guess that this issue occurred when I tried to highlight conflicts which can't be displayed on UI like the `mismatching groups`. So we can just filter not to highlight such conflicts. https://github.com/cvat-ai/cvat/blob/develop/cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-wrapper.tsx#L483

### Context

Error Message
```logs
TypeError
drawnState is undefined

deactivateShape@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:143205:11
deactivate@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:143249:10
highlight@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:143526:12
notify@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:142585:12
notify@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:147898:16
highlight@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:140847:10
highlight@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:140283:16
componentDidUpdate@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:179756:22
commitLifeCycles@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:442761:22
commitLayoutEffects@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:445729:23
callCallback@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:423114:14
invokeGuardedCallbackDev@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:423163:16
invokeGuardedCallback@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:423218:31
commitRootImpl@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:445467:30
unstable_runWithPriority@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:466190:12
runWithPriority$1@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:433965:10
commitRoot@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:445307:20
finishSyncRender@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:444733:13
performSyncWorkOnRoot@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:444719:23
../node_modules/react-dom/cjs/react-dom.development.js/flushSyncCallbackQueueImpl/<@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:434015:24
unstable_runWithPriority@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:466190:12
runWithPriority$1@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:433965:10
flushSyncCallbackQueueImpl@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:434010:24
flushSyncCallbackQueue@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:433998:3
batchedEventUpdates$1@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:444803:7
batchedEventUpdates@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:423721:12
dispatchEventForLegacyPluginEventSystem@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:426494:24
attemptToDispatchEvent@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:427193:44
dispatchEvent@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:427115:41
unstable_runWithPriority@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:466190:12
dispatchUserBlockingUpdate@http://localhost:3000/assets/cvat-ui.54562adfd37f714d4369.min.js:427098:18
```

The following was logged in the browser console,
```js console
Uncaught TypeError: drawnState is undefined
    deactivateShape canvasView.ts:2250
    deactivate canvasView.ts:2304
    highlight canvasView.ts:2614
    notify canvasView.ts:1557
    notify master.ts:27
    highlight canvasModel.ts:651
    highlight canvas.ts:113
    componentDidUpdate canvas-wrapper.tsx:492
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 5
    unstable_runWithPriority scheduler.development.js:653
    React 8
    unstable_runWithPriority scheduler.development.js:653
    dispatchUserBlockingUpdate React
canvasView.ts:2250:16
```
```js console
The above error occurred in the <CanvasWrapperComponent> component:
    in CanvasWrapperComponent (created by Connect(CanvasWrapperComponent))
    in Connect(CanvasWrapperComponent) (created by CanvasLayout)
    in div (created by GridItem)
    in Resizable (created by GridItem)
    in DraggableCore (created by GridItem)
    in GridItem (created by ReactGridLayout)
    in div (created by ReactGridLayout)
    in ReactGridLayout (created by WidthProvider)
    in WidthProvider (created by CanvasLayout)
    in main (created by Basic)
    in Basic (created by Content)
    in Content (created by CanvasLayout)
    in CanvasLayout
    in CanvasLayout (created by ReviewWorkspaceComponent)
    in section (created by BasicLayout)
    in BasicLayout (created by Layout)
    in Layout (created by ReviewWorkspaceComponent)
    in ReviewWorkspaceComponent (created by AnnotationPageComponent)
    in main (created by Basic)
    in Basic (created by Content)
    in Content (created by AnnotationPageComponent)
    in section (created by BasicLayout)
    in BasicLayout (created by Layout)
    in Layout (created by AnnotationPageComponent)
    in AnnotationPageComponent (created by Connect(AnnotationPageComponent))
    in Connect(AnnotationPageComponent) (created by Context.Consumer)
    in withRouter(Connect(AnnotationPageComponent)) (created by Context.Consumer)
    in Route (created by CVATApplication)
    in Switch (created by CVATApplication)
    in main (created by Basic)
    in Basic (created by Content)
    in Content (created by CVATApplication)
    in section (created by BasicLayout)
    in BasicLayout (created by Layout)
    in Layout (created by CVATApplication)
    in ShortcutsProvider (created by CVATApplication)
    in GlobalErrorBoundary (created by Connect(GlobalErrorBoundary))
    in Connect(GlobalErrorBoundary) (created by CVATApplication)
    in CVATApplication (created by Context.Consumer)
    in withRouter(CVATApplication) (created by Connect(withRouter(CVATApplication)))
    in Connect(withRouter(CVATApplication))
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider

React will try to recreate this component tree from scratch using the error boundary you provided, GlobalErrorBoundary. react-dom.development.js:19527
```

### PR DESCRIPTION
**Pull request by Viditagarwal7479**
Fixes #7775 

The UI crashes when hovering over the conflicts between the manual annotations and the GT annotations in the review mode.  
To fix this, I have added a check when the attributes `drawnState` and `shape` aren't present for certain conflicts, in such cases, we pass its value as `null` and thus skip the operation performed on those attributes.

### How has this been tested?
Follow the steps to reproduce the issue. After this PR, the mentioned issue will not occur thus UI will not crash.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
~- [ ] I have updated the documentation accordingly~
~- [ ] I have added tests to cover my changes~
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
~- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
Hi, did you have a chance to tests this with tag conflicts as well?

**Comment by Viditagarwal7479** [comment]
> Hi, did you have a chance to test this with tag conflicts as well?

Hello, tag conflict is a [different issue](https://github.com/cvat-ai/cvat/issues/7749) from this. 
The approach to the solution is similar. So, I think I should push the solution for that issue to this PR itself rather than creating a new PR.

**Comment by Viditagarwal7479** [comment]
Oh, my bad; this solution is sufficient for solving the tag annotation issue also. As the clientID corresponding to the tag conflicts isn't present in `drawnStates` and `svgShapes`, hence it gets skipped.

When the [deactivateShape](https://github.com/cvat-ai/cvat/blob/592c77f43a7a6c6ecba164b80a29294f153c2229/cvat-canvas/src/typescript/canvasView.ts#L2243) function is called this is the `clientID`, `this.drawnStates` and `this.svgShapes` respectively.
image

**Comment by klakhov** [comment]
Hi @Viditagarwal7479, Ive tried out the fix and here are some of my comments:
In general, while ignoring the `null`s works as a workaround for crashes it doesnt fix the actual problem, so I would suggest to invistigate the issues more deeply.

1. Lets talk firstly about tags conflicts. As I've already mentioned, the [higlight system code](https://github.com/cvat-ai/cvat/blob/develop/cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-wrapper.tsx#L483) from `cvat-ui` assumes that all the annotations highlighted annotations are on the canvas. But with your pr, after adding a tag conflict it is not right. Which means `cvat-ui` must understand that the conflict is about tags, filter it, and handle it properly(at least dont pass to cvanvasInstance).  Also, while just not passing it to canvasInstance will prevent crush, it wont provide good UX. It would be good to add highlight to tags aswell, we can handle it just in cvat-ui by watching `highlightedConflict` from the application store in `frame-tags` component. I would suggest to add this changes to your PR with updated UI for gt tags
2. The second thing is about `mismatching groups` conflicts crush. While trying out the issue's scenario Ive noticed that conflicts are not shown properly on the 0 frame. If I change the the frame and go back, the conflicts are rendered properly and no crush occurs. That means there is some bug in rendring conflicts at first place which we should invistigate and fix instead of just ignoring the `null`s.
Consider:
gt-problem

**Comment by Viditagarwal7479** [comment]
Hello @klakhov,
Thank you for your feedback.
1. Based on your feedback I have added this in this PR https://github.com/cvat-ai/cvat/pull/7774 since that PR was already having other commits related to how tags are being displayed in review mode. Now the tags will not be passed into highlight pipeline on the canvas, the size of tags with conflict will scale by 1.1 times and also come back to original size when new conflict is being hightlighted.
2. After going through the code also I am unable to figure out why this is happening, was surprised to see this happening.

**Comment by klakhov** [comment]
Ok, It seems its different issue wich is not connected to GT tags. Lets finish the tags PRs first.
You are free to investigate this issue further or we can just close this PR.

**Comment by zhiltsov-max** [comment]
No visible activity in this PR for 1 month, closing. Don't hesitate to reopen and continue.

**Pull request closed without merging**
