### PR TITLE
[GSoC2024] Modified Attribute Serializer to retain values after request

### PR DESCRIPTION
**Pull request by mach-12**
### Motivation and context

Fixing #6502: While creating or editing a multiline text attribute on a label, it was replacing the default newlines with commas.

image

This behavior was not appropriate. The cause of this issue was identified as the `DelimitedStringListField` serializer:

https://github.com/cvat-ai/cvat/blob/70a7cc0944ea1684defce29687d56529f7a24455/cvat/apps/engine/serializers.py#L226-L240

The fix was implemented by overriding the `to_representation()` method in the parent `AttributeSerializer`. This method converts the `ListField` into a list with only a single object with the text concatenated if the `input_type` in the context is 'text'.

Nested Label Serializers:
- `LabelSerializer`
  - `SublabelSerializer`
    - `AttributeSerializer`
      - `DelimitedStringListField`

### How has this been tested?

Changes persist as intended in the Tasks, Projects and Job views. 

Screenshot 2024-04-07 at 12 22 01 AM

Screenshot 2024-04-07 at 12 22 19 AM

image

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Review by Marishka17 — CHANGES_REQUESTED** [review]
Hello, thank you for the contribution.

I see one problem here:
In the current REST API implementation, it is possible to specify several values for text attributes too (even though it looks useless). But in that case, after these changes, all values will be merged into one and this is wrong. 

We use one [CharField](https://github.com/cvat-ai/cvat/blob/f1d308e8a01c72f51263aad9cb125d3031a95dcc/cvat/apps/engine/models.py#L860) to store values and [\n](https://github.com/cvat-ai/cvat/blob/f1d308e8a01c72f51263aad9cb125d3031a95dcc/cvat/apps/engine/serializers.py#L231) to separate them. Probably you can change the separator (e.g. `\\n`), but in that case, Django migration must be added.

**Comment by Marishka17** [comment]
> But how does a user trigger this intended use case in the first place

For example, users can use REST API directly

> How will the User know how to use it?

A user can check the server endpoint specification.

> So I need to:
> Define new separator,
> Add appropriate db Migration

It is possible to fix this issue using one more way - we can restrict specifying values for text attributes since this makes no sense at all. In that case, we don't need to change the separator.

IMHO, the second approach is more preferable.

**Comment by bsekachev** [comment]
Hi @mach-12 

Do you have any plans regarding the pull request?

**Comment by mach-12** [comment]
Yes, I need some help with understanding how to restrict specification of text values. Going to finish this PR

**Comment by bsekachev** [comment]
@Marishka17, please, work together with @mach-12 to finish the PR.

**Comment by Marishka17** [comment]
Hello @mach-12,  sorry for the delay, I'm going to close this PR now, but do not hesitate to reopen it when you implement more appropriate solution.

You can use the following approach to fix the issue:
- on the server: add `AttributeSerialize.validate` method and raise `ValidationError` if `values` is not empty and `input_type == models.AttributeType.TEXT` 
- on the server: add migration to clean the `values` field for all text attributes
- on the client: exclude sending default value in attribute `values` field for text attributes

**Pull request closed without merging**
