### PR TITLE
[GSoC2024]Import annotations keeping current ones(#4747)

### PR DESCRIPTION
**Pull request by EBayego**
This pull request keeps the current annotations without deleting them when new ones are imported, joining the current ones with the new ones.

### Motivation and context
This change is linked to issue #4747, and it arises from the need to preserve the current annotations instead of deleting them when new ones are imported. Now, in the annotations import window, there will be an option to keep the current annotations or not to keep them. To achieve this, the mentioned switch option has been added in the import window, and also a new API flag is created, which takes the value of the switch and forwards it to the backend logic, where it is processed and, if true, does not delete the current annotations.
image

### How has this been tested?
I have manually tested importing annotations with different formats and types, including having current annotations of all possible types to cover all possible cases. It has also been tested when the "keep old annotations" option is not checked, and in all cases, it works correctly. 
As for the code tests, if the current tests run successfully, it means that the new functionality of not deleting the annotations works correctly, as this is True by default. I am currently working on coding the tests to verify that importing also works when the current annotations are deleted.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

The test checkbox has not been checked due to the explanation provided in the previous section. I will mark it once the coded tests are developed.

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
Hi, please change the default to the old behvaior, so that all the existing clients could obtain the same results without any additional actions.

**Comment by nmanovic** [comment]
@EBayego , are you going to finish the PR?

**Comment by EBayego** [comment]
Yes, I want to finish it if you let me, but these days I don't have time to dedicate to it, I will do it as soon as possible.

**Comment by zhiltsov-max** [comment]
No visible activity in this PR for 1 month, closing. Don't hesitate to reopen and continue.

**Pull request closed without merging**
